on:
  push:
    branches: ["main"]

jobs:
  build: 
    name: Compilação
    runs-on: ubunto-latest

    steps:
    - name: Git Checkout
      uses: checkout@v3
    - name: Comfigure JDK 11
      uses: setup-java@v3
      with: 
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compilação
      run: mvn clean install -DskipTests

code-quality:
  name: Qualidade de código
  needs: build
  runs-on: ubunto-latest

  steps:
  - name: Git Checkout
    uses: checkout@v3 
  - name: Adicionando permissão para o mvnw
    run: chmod +x mvnw
  - name: Analise SonarCloud
    run: ./mvnw verity org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lab-crescer-pipeline
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

tests:
  name: Testes automatizados
  needs: code-quality
  runs-on: ubunto-latest

  steps:
  - name: Git Checkout
    uses: checkout@v3
  - name: Comfigure JDK 11
    uses: setup-java@v3
    with: 
      java-version: '11'
      distribution: 'temurin'
      cache: maven
  - name: Testes unitários
    run: mvn -B test --file pom.xml

push-image:
  name: Enviando imagem para o DockerHub
  needs: tests
  runs-on: ubunto-latest
  
  steps:
  - name: Login DockerHub
    uses: docker/login-action@v2
    with:
      username: ${{secrets.DOCKERHUB_USERNAME}}
      password: ${{secrets.DOCKERHUB_TOKEN}}

  - name: Criação e envio da image
    uses: docker/build-push-action@v4
    with:
      file: ./Dockerfile
      push: true
      run: |
        export DOCKER_BUILDKIT=0
        export COMPOSE_DOCKER_CLI_BUILD=0
      tag:
        lauraloch/javacrescer:latest

deploy:
  name: Publica app ACI
  needs: push-image
  runs-on: ubunto-latest

  steps:
  - name: Login via Azure CLI
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
  
  - name: Deploy da nossa aplicação Hello Java 
    uses: azure/aci-deploy@v1
    with:
      resource-group: RG-APPS-CRESCER
      dns-name-label: lab-crescer-laura-loch
      image: lauraloch/javacrescer:latest
      cpu: 1
      memory: 1
      registry-login-server: docker.io
      registry-username: ${{ secrets.REGISTRY_USERNAME }} 
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      name: lab-crescer-laura-loch
      location: 'east us'
